FEED_SLUG_TO_AUTHOR_STR = {
    "adelaide": "Department of Planning, Transport and Infrastructure [South Australia]",
    "antofagasta": "Subsecretaría de Transporte [Chile]",
    "detroit": "Department of Transportation (DDOT) [Detroit]",
    "kuopio": "City of Kuopio (Kuopion kaupunki)",
    "lisbon": "Transporlis",
    "luxembourg": "Bliksem Labs B.V., Stichting OpenGeo",
    "prague": "Dopravní podnik hl. m. Prahy a.s.",
    "athens": "Athens Urban Transport Organisation",
    "belfast": "ODI Belfast",
    "berlin": "VBB - Verkehrsverbund Berlin-Brandenburg GmbH",
    "bilbao": "Eusko Jaurlaritza / Basque Government",
    "bordeaux": "Bordeaux Métropole",
    "brisbane": "Queensland Government",
    "canberra": "ACT Government, Transport Canberra and City Services (Canberra), and Transport for New South Wales (Queanbeyan)",
    "dublin": "Transport For Ireland",
    "melbourne": "Victoria State Government, Public Transport Victoria",
    "grenoble": "MétroMobilité [Grenoble]",
    "nantes": "Nantes Métropole",
    "palermo": "Comune di Palermo, Area della Partecipazione, Decentramento, Servizi al Cittadino e Mobilità",
    "mallorca": "The Majorcan Transport Consortium",
    "paris": "Île-de-France Mobilités",
    "rennes": "Keolis Rennes",
    "rio_de_janeiro": "Fetranspor",
    "rome": "Roma Servizi per la Mobilità S.r.l.",
    "sydney": "Transport for New South Wales",
    "toulouse": "Tisséo",
    "turku": "Turun kaupungin joukkoliikennetoimisto (Public transport office of the city of Turku)",
    "valencia": "Valencia City Council",
    "valparaiso": "Subsecretaría de Transporte [Chile]",
    "venice": "ACTV SpA",
    "winnipeg": "Winnipeg Transit",
    "helsinki": "Helsinki Region Transport"
}